declare lower;
input optionSeriesPrefix = "230428";
input PutStrike = 175;
input CallStrike = 175;
input strikeSpacing = 1;
#{ ".5", default "1", "2.5", "5", "10", "25" };
input ShowAllLabels = no;
input Showput = no;
input Showput1 = no;
input Showput2 = no;
input Showput3 = no;
input Showput4 = no;
input Showput5 = no;
input Showput6 = no;
input Showput7 = no;
input Showput8 = no;
input Showput9 = no;
input Showput10 = no;
input Showput11 = no;
input Showput12 = no;
input Showput13 = no;
input Showput14 = no;
input Showput15 = no;
input Showput16 = no;
input Showput17 = no;
input Showput18 = no;
input Showput19 = no;
input Showput20 = no;
input  Showcall = no;
input  Showcall1 = no;
input  Showcall2 = no;
input  Showcall3 = no;
input  Showcall4 = no;
input  Showcall5 = no;
input  Showcall6 = no;
input  Showcall7 = no;
input  Showcall8 = no;
input  Showcall9 = no;
input  Showcall10 = no;
input  Showcall11 = no;
input  Showcall12 = no;
input  Showcall13 = no;
input  Showcall14 = no;
input  Showcall15 = no;
input  Showcall16 = no;
input  Showcall17 = no;
input  Showcall18 = no;
input  Showcall19 = no;
input  Showcall20 = no;
addlabel(1, getSymbol() + " Exp:" + optionSeriesPrefix + " CStrike:" + CallStrike + " PStrike:" + PutStrike, color.white);

### Put Option Volume
def putOptionVolume =  if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike)))));
def putOptionVolume1 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing)))));
def putOptionVolume2 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing)))));
def putOptionVolume3 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume4 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume5 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume6 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume7 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume8 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume9 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume10 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume11 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume12 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume13 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume14 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume15 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume16 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume17 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume18 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume19 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionVolume20 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));

####Call Option Volume
def callOptionVolume =  if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike)))));
def callOptionVolume1 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing)))));
def callOptionVolume2 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing)))));
def callOptionVolume3 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume4 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume5 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume6 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume7 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume8 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume9 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume10 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume11 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume12 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume13 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume14 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume15 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume16 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume17 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume18 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume19 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionVolume20 = if IsNaN(volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else volume(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
### Put Option ohlc4
def putOptionohlc4 =  if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike)))));
def putOptionohlc41 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing)))));
def putOptionohlc42 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing)))));
def putOptionohlc43 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc44 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc45 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc46 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc47 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc48 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc49 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc410 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc411 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc412 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc413 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc414 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc415 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc416 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc417 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc418 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc419 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptionohlc420 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));

####Call Option ohlc4
def callOptionohlc4 =  if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike)))));
def callOptionohlc41 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing)))));
def callOptionohlc42 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing)))));
def callOptionohlc43 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc44 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc45 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc46 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc47 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc48 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc49 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc410 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc411 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc412 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc413 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc414 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc415 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc416 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc417 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc418 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc419 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptionohlc420 = if IsNaN(ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else ohlc4(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));

plot Putvol = (putOptionVolume * putOptionohlc4 * 100) + (putOptionVolume1 * putOptionohlc41 * 100) + (putOptionVolume2 * putOptionohlc42 * 100) + (putOptionVolume3 * putOptionohlc43 * 100) + (putOptionVolume4 * putOptionohlc44 * 100) + (putOptionVolume5 * putOptionohlc45 * 100) + (putOptionVolume6 * putOptionohlc46 * 100) + (putOptionVolume7 * putOptionohlc47 * 100) + (putOptionVolume8 * putOptionohlc48 * 100) + (putOptionVolume9 * putOptionohlc49 * 100) + (putOptionVolume10 * putOptionohlc410 * 100) + (putOptionVolume11 * putOptionohlc411 * 100) + (putOptionVolume12 * putOptionohlc412 * 100) + (putOptionVolume13 * putOptionohlc413 * 100) + (putOptionVolume14 * putOptionohlc414 * 100) + (putOptionVolume15 * putOptionohlc415 * 100) + (putOptionVolume16 * putOptionohlc416 * 100) + (putOptionVolume17 * putOptionohlc417 * 100) + (putOptionVolume18 * putOptionohlc418 * 100) + (putOptionVolume19 * putOptionohlc419 * 100) + (putOptionVolume20 * putOptionohlc420 * 100);
plot Callvol = (callOptionVolume * callOptionohlc4 * 100) + (callOptionVolume1 * callOptionohlc41 * 100) + (callOptionVolume2 * callOptionohlc42 * 100) + (callOptionVolume3 * callOptionohlc43 * 100) + (callOptionVolume4 * callOptionohlc44 * 100) + (callOptionVolume5 * callOptionohlc45 * 100) + (callOptionVolume6 * callOptionohlc46 * 100) + (callOptionVolume7 * callOptionohlc47 * 100) + (callOptionVolume8 * callOptionohlc48 * 100) + (callOptionVolume9 * callOptionohlc49 * 100) + (callOptionVolume10 * callOptionohlc410 * 100) + (callOptionVolume11 * callOptionohlc411 * 100) + (callOptionVolume12 * callOptionohlc412 * 100) + (callOptionVolume13 * callOptionohlc413 * 100) + (callOptionVolume14 * callOptionohlc414 * 100) + (callOptionVolume15 * callOptionohlc415 * 100) + (callOptionVolume16 * callOptionohlc416 * 100) + (callOptionVolume17 * callOptionohlc417 * 100) + (callOptionVolume18 * callOptionohlc418 * 100) + (callOptionVolume19 * callOptionohlc419 * 100) + (callOptionVolume20 * callOptionohlc420 * 100);

Putvol.SetPaintingStrategy(PaintingStrategy.LINE);
Callvol.SetPaintingStrategy(PaintingStrategy.LINE);
Putvol.SetDefaultColor(Color.RED);
Callvol.SetDefaultColor(Color.CYAN);
AddCloud(Callvol, Putvol, Color.CYAN, Color.RED);
plot ZeroLine = 0;
ZeroLine.SetDefaultColor(Color.GRAY);
AddCloud(Callvol, ZeroLine, Color.CYAN, Color.RED);
AddCloud(Putvol, ZeroLine, Color.RED, Color.CYAN);
AddLabel(Showcall or ShowAllLabels, Concat("C", CallStrike) + ":  " + callOptionVolume, Color.CYAN);
AddLabel(Showcall1 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing) + ":  " + callOptionVolume1, Color.CYAN);
AddLabel(Showcall2 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume2, Color.CYAN);
AddLabel(Showcall3 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume3, Color.CYAN);
AddLabel(Showcall4 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume4, Color.CYAN);
AddLabel(Showcall5 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume5, Color.CYAN);
AddLabel(Showcall6 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume6, Color.CYAN);
AddLabel(Showcall7 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume7, Color.CYAN);
AddLabel(Showcall8 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume8, Color.CYAN);
AddLabel(Showcall9 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume9, Color.CYAN);
AddLabel(Showcall10 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume10, Color.CYAN);
AddLabel(Showcall11 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume11, Color.CYAN);
AddLabel(Showcall12 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume12, Color.CYAN);
AddLabel(Showcall13 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume13, Color.CYAN);
AddLabel(Showcall14 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume14, Color.CYAN);
AddLabel(Showcall15 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume15, Color.CYAN);
AddLabel(Showcall16 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume16, Color.CYAN);
AddLabel(Showcall17 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume17, Color.CYAN);
AddLabel(Showcall18 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume18, Color.CYAN);
AddLabel(Showcall19 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume19, Color.CYAN);
AddLabel(Showcall20 or ShowAllLabels, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing) + ":  " + callOptionVolume20, Color.CYAN);
AddLabel(Showput or ShowAllLabels, Concat("P", PutStrike) + ":  " + putOptionVolume);
AddLabel(Showput1 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing) + ":  " + putOptionVolume1);
AddLabel(Showput2 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume2);
AddLabel(Showput3 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume3);
AddLabel(Showput4 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume4);
AddLabel(Showput5 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume5);
AddLabel(Showput6 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume6);
AddLabel(Showput7 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume7);
AddLabel(Showput8 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume8);
AddLabel(Showput9 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume9);
AddLabel(Showput10 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume10);
AddLabel(Showput11 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume11);
AddLabel(Showput12 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume12);
AddLabel(Showput13 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume13);
AddLabel(Showput14 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume14);
AddLabel(Showput15 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume15);
AddLabel(Showput16 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume16);
AddLabel(Showput17 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume17);
AddLabel(Showput18 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume18);
AddLabel(Showput19 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume19);
AddLabel(Showput20 or ShowAllLabels, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing) + ":  " + putOptionVolume20);


### Put Option tick_count
def putOptiontick_count =  if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike)))));
def putOptiontick_count1 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing)))));
def putOptiontick_count2 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing)))));
def putOptiontick_count3 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count4 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count5 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count6 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count7 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count8 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count9 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count10 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count11 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count12 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count13 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count14 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count15 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count16 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count17 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count18 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count19 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));
def putOptiontick_count20 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("P", PutStrike - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing - strikeSpacing)))));

####Call Option tick_count
def callOptiontick_count =  if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike)))));
def callOptiontick_count1 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing)))));
def callOptiontick_count2 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing)))));
def callOptiontick_count3 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count4 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count5 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count6 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count7 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count8 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count9 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count10 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count11 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count12 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count13 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count14 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count15 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count16 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count17 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count18 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count19 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));
def callOptiontick_count20 = if IsNaN(tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))))) then 0 else tick_count(Concat(".", Concat(GetSymbol(), Concat(optionseriesprefix, Concat("C", CallStrike + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing + strikeSpacing)))));

def Puttick = putOptiontick_count + putOptiontick_count1 + putOptiontick_count2 + putOptiontick_count3 + putOptiontick_count4 + putOptiontick_count5 + putOptiontick_count6 + putOptiontick_count7 + putOptiontick_count8 + putOptiontick_count9 + putOptiontick_count10 + putOptiontick_count11 + putOptiontick_count12 + putOptiontick_count13 + putOptiontick_count14 + putOptiontick_count15 + putOptiontick_count16 + putOptiontick_count17 + putOptiontick_count18 + putOptiontick_count19 + putOptiontick_count20;
def Calltick = callOptiontick_count + callOptiontick_count1 + callOptiontick_count2 + callOptiontick_count3 + callOptiontick_count4 + callOptiontick_count5 + callOptiontick_count6 + callOptiontick_count7 + callOptiontick_count8 + callOptiontick_count9 + callOptiontick_count10 + callOptiontick_count11 + callOptiontick_count12 + callOptiontick_count13 + callOptiontick_count14 + callOptiontick_count15 + callOptiontick_count16 + callOptiontick_count17 + callOptiontick_count18 + callOptiontick_count19 + callOptiontick_count20;

#Puttick.SetPaintingStrategy(PaintingStrategy.LINE);
#Calltick.SetPaintingStrategy(PaintingStrategy.LINE);
#Puttick.SetDefaultColor(Color.light_red);
#Calltick.SetDefaultColor(Color.plum);
#AddCloud(Calltick, Puttick, Color.plum, Color.light_RED);

#AddCloud(Calltick, ZeroLine, Color.CYAN, Color.RED);
#AddCloud(Puttick, ZeroLine, Color.RED, Color.CYAN);

###################################
#StudyName: Dilbert_BlockTrade_V1
#Description:  Identify bars with high volume relative to the tick_count.Such bars could indicate a block trade, or a possible change in trend.
    #Author: Dilbert
#Requested By:
# Ver     Date     Auth      Change
# V1      090717   Dilbert   1st code cut
# TOS.mx Link:
# Trading Notes:  Identify bars with high volume relative to the tick_count.Such bars could indicate a block trade, or a possible change in trend.


#PUT RATIO
input AvgType = AverageType.EXPONENTIAL;
input MaLength = 20;
def V = Putvol;
def TC = Puttick;
def TradeSize = V / TC;

input displace = 0;
input SdLength = 20;
input Num_Dev_up = 2.0;
input averageType = AverageType.SIMPLE;

def sDev = StDev(data = TradeSize[-displace], length = SdLength);

def MA = MovingAverage(AvgType, TradeSize, MaLength);
plot Dot = if TradeSize > Ma + (sDev * Num_Dev_up) then Putvol else Double.NaN;
Dot.SetPaintingStrategy(PaintingStrategy.Points);
Dot.SetLineWeight(5);
Dot.AssignValueColor(color.red);

#CALL RATIO
input AvgType1 = AverageType.EXPONENTIAL;
input MaLength1 = 20;
def V1 = Callvol;
def TC1 = Calltick;
def TradeSize1 = V1 / TC1;

input displace1 = 0;
input SdLength1 = 20;
input Num_Dev_up1 = 2.0;
input averageType1 = AverageType.SIMPLE;

def sDev1 = StDev(data = TradeSize1[-displace1], length = SdLength1);

def MA1 = MovingAverage(AvgType1, TradeSize1, MaLength1);
plot Dot1 = if TradeSize1 > Ma1 + (sDev1 * Num_Dev_up1) then Callvol else Double.NaN;
Dot1.SetPaintingStrategy(PaintingStrategy.Points);
Dot1.SetLineWeight(5);
Dot1.AssignValueColor(color.cyan);